// NOTE: This file is auto-generated by React Cosmos.
// It imports all fixture and decorator modules, making them available to the
// React Cosmos renderer along with the renderer config.

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core';

import * as fixture0 from './components/__fixtures__/heading';
import * as fixture1 from './components/__fixtures__/hero';

export const rendererConfig: RendererConfig = {
  "webSocketUrl": "ws://192.168.29.31:5000",
  "rendererUrl": "http://localhost:3000/cosmos/<fixture>"
};

const fixtures = {
  'components/__fixtures__/heading.tsx': { module: fixture0 },
  'components/__fixtures__/hero.tsx': { module: fixture1 }
};

const decorators = {};

export const moduleWrappers: UserModuleWrappers = {
  lazy: false,
  fixtures,
  decorators
};
